version: 1.1.{build}
skip_tags: true
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - preview
image:
  - Visual Studio 2017
init:
  - pwsh: |
      "APPVEYOR_REPO_BRANCH = $env:APPVEYOR_REPO_BRANCH"
      "APPVEYOR_PULL_REQUEST_NUMBER = $env:APPVEYOR_PULL_REQUEST_NUMBER"
      "APPVEYOR_REPO_COMMIT_MESSAGE = $env:APPVEYOR_REPO_COMMIT_MESSAGE"
      "APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED = $env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED"
      "OS = $env:OS"
  - sh: export PATH=/home/appveyor/.local/bin:$PATH
environment:
  POWERSHELL_TELEMETRY_OPTOUT: 1
  # Avoid expensive initialization of dotnet cli, see: http://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  PowershellGalleryKey:
    secure: UW8cAeuSOxzbp1qgpo+fsy5gvMmvoKJ+qwZvmLZ+CgLoLcxvLfrHEUfOO5s3YNc5
install:
  - ps: |
      import-module powershellget
      # cannot update and use new version in the same process
      #Install-module PowerShellGet -force -AllowClobber -SkipPublisherCheck -Scope CurrentUser
      #Remove-Module PowerShellGet -Force
      #Import-Module PowerShellGet -Force
      Get-PackageProvider -Name NuGet -ForceBootstrap
      Install-Module PSScriptAnalyzer -MaximumVersion 1.18.2 -force -AllowClobber -SkipPublisherCheck -Scope CurrentUser
      Install-Module pester -MaximumVersion 4.10.1 -force -AllowClobber -SkipPublisherCheck -Scope CurrentUser
      install-module PlatyPS -force -AllowClobber -SkipPublisherCheck -Scope CurrentUser
  - pwsh: |
      import-module powershellget
      # cannot update and use new version in the same process
      #Install-module PowerShellGet -force -AllowClobber -SkipPublisherCheck -Scope CurrentUser
      #Remove-Module PowerShellGet -Force
      #Import-Module PowerShellGet -Force
      Get-PackageProvider -Name NuGet -ForceBootstrap
      Install-Module PSScriptAnalyzer -MaximumVersion 1.18.2 -force -AllowClobber -SkipPublisherCheck -Scope CurrentUser
      Install-Module pester -MaximumVersion 4.10.1 -force -AllowClobber -SkipPublisherCheck -Scope CurrentUser
      install-module PlatyPS -force -AllowClobber -SkipPublisherCheck -Scope CurrentUser
build_script:
  - pwsh: |
      if( $env:APPVEYOR_REPO_BRANCH -in @("master","preview") -and !$env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_REPO_COMMIT_MESSAGE -notlike "skip: *" ) {
        .\Invoke-Build.ps1 build,test,publish
      } else {
        .\Invoke-Build.ps1 build,buildhelp,test
      }
artifacts:
  - path: PulumiSH.zip
deploy:
  - provider: GitHub
    tag: $(APPVEYOR_BUILD_VERSION)
    auth_token:
      secure: DS8SjIPNW5c1zpn7AOrdK7ySlLwWB0/Kj21EZVIy1/pwE/LLfoxoXLfh6VYC6+X2
    draft: true
    on:
      APPVEYOR_REPO_BRANCH: master
  - provider: GitHub
    tag: $(APPVEYOR_BUILD_VERSION)
    auth_token:
      secure: DS8SjIPNW5c1zpn7AOrdK7ySlLwWB0/Kj21EZVIy1/pwE/LLfoxoXLfh6VYC6+X2
    draft: true
    on:
      APPVEYOR_REPO_BRANCH: preview
